// visaData.js — Central data file for all visa booking pages
// Usage: import { getVisaData, visaList } from './visaData';
// Pass visaId (e.g. "uae-30", "uae-14", "thailand") to getVisaData()

export const visaList = [
  { id: "uae-30",    country: "UAE",       city: "Dubai",        flag: "🇦🇪", label: "30 Days Tourist" },
  { id: "uae-14",    country: "UAE",       city: "Abu Dhabi",    flag: "🇦🇪", label: "14 Days Tourist" },
  { id: "thailand",  country: "Thailand",  city: "Bangkok",      flag: "🇹🇭", label: "Tourist Visa" },
  { id: "singapore", country: "Singapore", city: "Singapore",    flag: "🇸🇬", label: "Tourist Visa" },
  { id: "malaysia",  country: "Malaysia",  city: "Kuala Lumpur", flag: "🇲🇾", label: "eNTRI / eVisa" },
  { id: "usa",       country: "USA",       city: "New York",     flag: "🇺🇸", label: "B1/B2 Tourist" },
];

const DATA = {
  "uae-30": {
    heroImg: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1600&q=85",
    heroAlt: "Dubai skyline",
    breadcrumb: ["Home", "UAE", "Dubai Visa"],
    title: "Dubai",
    flag: "🇦🇪",
    country: "UAE",
    subtitle: "for Indians",
    pills: [
      { icon: "🛡️", text: "Guaranteed in", strong: "4 days" },
      { text: "📱 E-Visa · Paperless" },
      { text: "🔒 100% Refund Policy" },
    ],
    stats: [
      ["53K+", "Visas Processed"],
      ["4 Days", "Guaranteed"],
      ["4.9★", "12K+ Reviews"],
      ["₹6,800", "Govt Fee Only"],
    ],
    guaranteeText: "Guaranteed by 11th Mar, 09:29 PM",
    fasterText: "11 hrs faster",
    govFee: 6800,
    svcFee: 999,
    svcOrig: 1500,
    visaTypes: ["Tourism", "Business", "Transit", "Student"],
    visaInfo: [
      { icon: "📱", label: "Visa Type",      value: "E-Visa",    link: false },
      { icon: "📅", label: "Length of Stay", value: "30 days",   link: true  },
      { icon: "✅", label: "Validity",        value: "60 days",   link: true  },
      { icon: "🚪", label: "Entry",           value: "Single",    link: true  },
      { icon: "📂", label: "Method",          value: "Paperless", link: true  },
    ],
    timeslots: [
      { days: "4 days", date: "11 Mar 2026", time: "09:29 PM" },
      { days: "4 days", date: "11 Mar 2026", time: "10:29 AM" },
      { days: "5 days", date: "12 Mar 2026", time: "11:00 AM" },
    ],
    slotSectionTitle: "Get a Guaranteed Visa on",
    emirates: [
      { name: "Dubai",          img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80" },
      { name: "Abu Dhabi",      img: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80" },
      { name: "Sharjah",        img: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80" },
      { name: "Ras Al Khaimah", img: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=600&q=80" },
      { name: "Fujairah",       img: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80" },
      { name: "Umm Al Quwain",  img: "https://images.unsplash.com/photo-1548700960-927acf3b1dc0?w=600&q=80" },
      { name: "Ajman",          img: "https://images.unsplash.com/photo-1526495124232-a04e1849168c?w=600&q=80" },
    ],
    emiratesSectionTitle: "All 7 Emirates with 1 Visa",
    requirements: [
      { icon: "🛂", title: "Passport",         desc: "Valid for at least 6 months from your travel date" },
      { icon: "🖼️", title: "Passport Photo",   desc: "Recent photo, white background, taken within 6 months" },
      { icon: "✈️", title: "Return Ticket",    desc: "Confirmed return flight booking" },
      { icon: "🏨", title: "Hotel Booking",    desc: "Confirmed accommodation for your entire stay" },
      { icon: "💳", title: "Bank Statement",   desc: "Last 3 months showing sufficient funds" },
      { icon: "📋", title: "Travel Insurance", desc: "Adequate coverage for the duration of your trip" },
    ],
    partners: [
      { abbr: "MOFA", name: "Ministry of Foreign Affairs", color: "#1a3a5c" },
      { abbr: "GOV",  name: "Government of Dubai",          color: "#8b1a1a" },
      { abbr: "IATA", name: "International Air Transport",  color: "#00538b" },
    ],
    steps: [
      { icon: "📝", num: "01", title: "Apply on TheVisa",    desc: "Submit documents online — only pay the government fee upfront, nothing else." },
      { icon: "🔍", num: "02", title: "Documents Verified",    desc: "Our visa experts personally review every document before submission." },
      { icon: "⚙️", num: "03", title: "Visa Gets Processed",   desc: "We coordinate with Immigration to ensure timely, accurate processing." },
      { icon: "🎉", num: "04", title: "Visa Delivered to You", desc: "Receive your approved e-Visa via email — ready to fly!" },
    ],
    reviews: [
      { name: "Ananya Sharma",  flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Super fast & stress-free!",       body: "Got my UAE visa in just 3 days. Completely paperless and the team was incredibly helpful. Will definitely use TheVisa again!" },
      { name: "Rohit Verma",    flag: "🇮🇳", rating: 5, date: "Jan 2026", title: "100% recommended",                body: "Received my visa within the guaranteed timeframe. All fees were shown upfront — zero hidden charges. Brilliant service." },
      { name: "Priya Nair",     flag: "🇮🇳", rating: 5, date: "Mar 2026", title: "Professional & transparent",     body: "Loved how transparent the pricing was. Got my visa exactly when promised. Will recommend to everyone I know!" },
      { name: "Karan Mehta",    flag: "🇮🇳", rating: 4, date: "Feb 2026", title: "Great experience overall",       body: "Seamless application process. Support team responded instantly on WhatsApp. Minor query resolved in minutes." },
      { name: "Sneha Kulkarni", flag: "🇮🇳", rating: 5, date: "Jan 2026", title: "Fastest visa I've ever gotten!", body: "Skeptical at first but TheVisa delivered in under 4 days. The timeline tracker is brilliant — knew every step in real time." },
      { name: "Arjun Bose",     flag: "🇮🇳", rating: 5, date: "Mar 2026", title: "Seamless process",               body: "Family visa for 4 people done perfectly. 24/7 customer care answered every question patiently. Exceptional team!" },
    ],
    reviewScore: "4.9",
    reviewCount: "12,400+",
    faqs: [
      { q: "How long does a UAE visa take?",                    a: "With TheVisa, your UAE tourist visa is guaranteed in 4 days. Urgent same-day processing is also available. Our on-time guarantee means zero service fees if we cause any delay." },
      { q: "What is the total cost of a UAE visa for Indians?", a: "Government fee: ₹6,800 (paid upfront). TheVisa service fee: ₹999 (paid only after your visa is approved). Total: ₹7,799. Zero hidden charges, ever." },
      { q: "Can I visit all 7 Emirates with one visa?",         a: "Yes! A single UAE visa gives full access to all 7 Emirates — Dubai, Abu Dhabi, Sharjah, Ras Al Khaimah, Fujairah, Umm Al Quwain, and Ajman." },
      { q: "Is UAE visa on arrival available for Indians?",     a: "No. Indians must apply for a UAE e-Visa before travelling. TheVisa handles this 100% online — no embassy visit needed." },
      { q: "What documents are required?",                      a: "Valid passport (6+ months), recent passport photo, confirmed return tickets, hotel booking, and 3 months bank statement. TheVisa sends a detailed checklist after you apply." },
      { q: "What is TheVisa Protect?",                        a: "TheVisa Protect is included FREE with every application. If your visa is delayed — you pay zero service fees. If rejected — 100% refund guaranteed." },
      { q: "Can I extend my UAE visa after arrival?",           a: "Yes, UAE tourist visas can be extended once for an additional 30 days. Contact our support team for extension assistance." },
    ],
    authBadge: "TheVisa is authorized by the Government of Dubai",
    destinationGridTitle: "All 7 Emirates with 1 Visa",
  },

  "uae-14": {
    heroImg: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1600&q=85",
    heroAlt: "Abu Dhabi skyline",
    breadcrumb: ["Home", "UAE", "Abu Dhabi Visa"],
    title: "Abu Dhabi",
    flag: "🇦🇪",
    country: "UAE",
    subtitle: "for Indians",
    pills: [
      { icon: "🛡️", text: "Guaranteed in", strong: "3 days" },
      { text: "📱 E-Visa · Paperless" },
      { text: "🔒 100% Refund Policy" },
    ],
    stats: [
      ["53K+", "Visas Processed"],
      ["3 Days", "Guaranteed"],
      ["4.9★", "12K+ Reviews"],
      ["₹4,500", "Govt Fee Only"],
    ],
    guaranteeText: "Guaranteed by 10th Mar, 11:00 AM",
    fasterText: "9 hrs faster",
    govFee: 4500,
    svcFee: 799,
    svcOrig: 1200,
    visaTypes: ["Tourism", "Business", "Transit"],
    visaInfo: [
      { icon: "📱", label: "Visa Type",      value: "E-Visa",    link: false },
      { icon: "📅", label: "Length of Stay", value: "14 days",   link: true  },
      { icon: "✅", label: "Validity",        value: "30 days",   link: true  },
      { icon: "🚪", label: "Entry",           value: "Single",    link: true  },
      { icon: "📂", label: "Method",          value: "Paperless", link: true  },
    ],
    timeslots: [
      { days: "3 days", date: "10 Mar 2026", time: "11:00 AM" },
      { days: "3 days", date: "10 Mar 2026", time: "03:00 PM" },
      { days: "4 days", date: "11 Mar 2026", time: "09:00 AM" },
    ],
    slotSectionTitle: "Get a Guaranteed Visa on",
    emirates: [
      { name: "Dubai",          img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80" },
      { name: "Abu Dhabi",      img: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80" },
      { name: "Sharjah",        img: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80" },
      { name: "Ras Al Khaimah", img: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=600&q=80" },
      { name: "Fujairah",       img: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80" },
      { name: "Umm Al Quwain",  img: "https://images.unsplash.com/photo-1548700960-927acf3b1dc0?w=600&q=80" },
      { name: "Ajman",          img: "https://images.unsplash.com/photo-1526495124232-a04e1849168c?w=600&q=80" },
    ],
    emiratesSectionTitle: "All 7 Emirates with 1 Visa",
    requirements: [
      { icon: "🛂", title: "Passport",         desc: "Valid for at least 6 months from your travel date" },
      { icon: "🖼️", title: "Passport Photo",   desc: "Recent photo, white background, taken within 6 months" },
      { icon: "✈️", title: "Return Ticket",    desc: "Confirmed return flight booking" },
      { icon: "🏨", title: "Hotel Booking",    desc: "Confirmed accommodation for your entire stay" },
      { icon: "💳", title: "Bank Statement",   desc: "Last 3 months showing sufficient funds" },
    ],
    partners: [
      { abbr: "MOFA", name: "Ministry of Foreign Affairs", color: "#1a3a5c" },
      { abbr: "GOV",  name: "Government of UAE",            color: "#8b1a1a" },
      { abbr: "IATA", name: "International Air Transport",  color: "#00538b" },
    ],
    steps: [
      { icon: "📝", num: "01", title: "Apply on TheVisa",    desc: "Submit documents online — only pay the government fee upfront, nothing else." },
      { icon: "🔍", num: "02", title: "Documents Verified",    desc: "Our visa experts personally review every document before submission." },
      { icon: "⚙️", num: "03", title: "Visa Gets Processed",   desc: "We coordinate with UAE Immigration for timely, accurate processing." },
      { icon: "🎉", num: "04", title: "Visa Delivered to You", desc: "Receive your approved e-Visa via email — ready to fly!" },
    ],
    reviews: [
      { name: "Meera Iyer",    flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Quick 14-day visa!",             body: "Perfect for a short holiday. Got the 14-day visa in under 3 days. Pricing was clear and transparent from start to finish." },
      { name: "Suresh Pillai", flag: "🇮🇳", rating: 5, date: "Jan 2026", title: "Very smooth process",            body: "Applied for 14 days, got it in 2 days. Great service and very professional team at TheVisa." },
      { name: "Nisha Singh",   flag: "🇮🇳", rating: 4, date: "Mar 2026", title: "Reliable and fast",             body: "Used for a business trip. Short turnaround and the team kept me updated at every step. Highly recommended." },
      { name: "Amit Desai",    flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Best visa service!",            body: "Second time using TheVisa for the 14-day UAE visa. Same quality service both times. Will keep coming back!" },
    ],
    reviewScore: "4.9",
    reviewCount: "12,400+",
    faqs: [
      { q: "How long does the 14-day UAE visa take?",           a: "With TheVisa, your 14-day UAE visa is guaranteed in 3 days. Urgent processing is also available." },
      { q: "What is the cost of a 14-day UAE visa for Indians?", a: "Government fee: ₹4,500 (paid upfront). TheVisa service fee: ₹799 (paid after approval). Total: ₹5,299. Zero hidden charges." },
      { q: "Can I visit all Emirates on a 14-day visa?",        a: "Yes, the 14-day UAE visa gives access to all 7 Emirates with no restrictions on which you visit." },
      { q: "Is the 14-day visa extendable?",                    a: "The 14-day visa cannot be extended. If you need more time, you'll need to apply for a new 30-day visa. Contact our team for guidance." },
      { q: "What documents are needed?",                        a: "Valid passport (6+ months), passport photo, return tickets, hotel booking, and bank statement. Full checklist sent after application." },
    ],
    authBadge: "TheVisa is authorized by the Government of UAE",
    destinationGridTitle: "All 7 Emirates with 1 Visa",
  },

  "thailand": {
    heroImg: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&q=85",
    heroAlt: "Bangkok Thailand",
    breadcrumb: ["Home", "Thailand", "Bangkok Visa"],
    title: "Thailand",
    flag: "🇹🇭",
    country: "Thailand",
    subtitle: "for Indians",
    pills: [
      { icon: "🛡️", text: "Guaranteed in", strong: "5 days" },
      { text: "📱 E-Visa · Online" },
      { text: "🔒 100% Refund Policy" },
    ],
    stats: [
      ["28K+", "Visas Processed"],
      ["5 Days", "Guaranteed"],
      ["4.8★", "8K+ Reviews"],
      ["₹3,200", "Govt Fee Only"],
    ],
    guaranteeText: "Guaranteed by 12th Mar, 06:00 PM",
    fasterText: "8 hrs faster",
    govFee: 3200,
    svcFee: 799,
    svcOrig: 1299,
    visaTypes: ["Tourism", "Business", "Medical", "Transit"],
    visaInfo: [
      { icon: "📱", label: "Visa Type",      value: "TR Visa",   link: false },
      { icon: "📅", label: "Length of Stay", value: "30 days",   link: true  },
      { icon: "✅", label: "Validity",        value: "90 days",   link: true  },
      { icon: "🚪", label: "Entry",           value: "Single",    link: true  },
      { icon: "📂", label: "Method",          value: "E-Visa",    link: true  },
    ],
    timeslots: [
      { days: "5 days", date: "12 Mar 2026", time: "06:00 PM" },
      { days: "5 days", date: "12 Mar 2026", time: "08:00 PM" },
      { days: "6 days", date: "13 Mar 2026", time: "10:00 AM" },
    ],
    slotSectionTitle: "Get a Guaranteed Visa on",
    emirates: [
      { name: "Bangkok",     img: "https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=600&q=80" },
      { name: "Phuket",      img: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=600&q=80" },
      { name: "Chiang Mai",  img: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=600&q=80" },
      { name: "Pattaya",     img: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=80" },
      { name: "Koh Samui",   img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80" },
      { name: "Krabi",       img: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=600&q=80" },
      { name: "Hua Hin",     img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80" },
    ],
    emiratesSectionTitle: "Top Destinations Covered",
    requirements: [
      { icon: "🛂", title: "Passport",          desc: "Valid for at least 6 months from your travel date" },
      { icon: "🖼️", title: "Passport Photo",    desc: "Recent photo on white background, taken within 6 months" },
      { icon: "✈️", title: "Return Ticket",     desc: "Confirmed return flight booking" },
      { icon: "🏨", title: "Hotel Booking",     desc: "Confirmed accommodation for your entire stay" },
      { icon: "💳", title: "Bank Statement",    desc: "Last 3 months — must show minimum ₹50,000 balance" },
      { icon: "📋", title: "Travel Insurance",  desc: "Minimum coverage of USD 50,000 recommended" },
    ],
    partners: [
      { abbr: "MOI",  name: "Ministry of Interior, Thailand", color: "#1a5c2e" },
      { abbr: "TAT",  name: "Tourism Authority of Thailand",  color: "#8b4513" },
      { abbr: "IATA", name: "International Air Transport",    color: "#00538b" },
    ],
    steps: [
      { icon: "📝", num: "01", title: "Apply on TheVisa",    desc: "Submit documents online — only pay the government fee upfront, nothing else." },
      { icon: "🔍", num: "02", title: "Documents Verified",    desc: "Our visa experts review and translate documents if required before submission." },
      { icon: "⚙️", num: "03", title: "Visa Gets Processed",   desc: "We coordinate with Thai Immigration for timely and accurate processing." },
      { icon: "🎉", num: "04", title: "Visa Delivered to You", desc: "Receive your e-Visa via email — print and carry for entry at Thai border." },
    ],
    reviews: [
      { name: "Pooja Menon",   flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Thailand made easy!",            body: "Got my Thailand visa in 4 days. The team was super responsive and even helped me fill out the forms correctly. 10/10!" },
      { name: "Rahul Kapoor",  flag: "🇮🇳", rating: 5, date: "Jan 2026", title: "Stress-free holiday prep",       body: "TheVisa made the Thailand visa process completely hassle-free. Approved before the guaranteed date!" },
      { name: "Divya Reddy",   flag: "🇮🇳", rating: 4, date: "Mar 2026", title: "Great service, minor delay",    body: "Got visa in 6 days (1 day past guarantee) but they waived the service fee as promised. Honest and transparent." },
      { name: "Vikram Nair",   flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Will use again!",               body: "Third time using TheVisa — this time for Thailand. Consistent quality every single time. Highly recommended!" },
    ],
    reviewScore: "4.8",
    reviewCount: "8,000+",
    faqs: [
      { q: "Do Indians need a visa for Thailand?",              a: "Indians no longer get visa-on-arrival free as of 2025. Apply online via TheVisa — we process your Thai TR visa within 5 guaranteed days." },
      { q: "What is the cost of a Thailand visa for Indians?",  a: "Government fee: ₹3,200 (paid upfront). TheVisa service fee: ₹799 (paid after visa approval). Total: ₹3,999." },
      { q: "How long can I stay in Thailand?",                  a: "A standard Thai tourist visa allows a 30-day stay, which can be extended once for another 30 days at an immigration office in Thailand." },
      { q: "Can I apply for a multiple-entry Thailand visa?",   a: "Yes, a Multiple Entry Tourist Visa (METV) is available, valid for 6 months with 60 days per entry. Ask our team for details." },
      { q: "What documents are required for Thailand visa?",    a: "Passport (6+ months), passport photo, return tickets, hotel booking, and bank statement showing ₹50,000+ balance. Full checklist provided after application." },
    ],
    authBadge: "TheVisa is authorized by the Royal Thai Embassy",
    destinationGridTitle: "Top Destinations Covered",
  },

  "singapore": {
    heroImg: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1600&q=85",
    heroAlt: "Singapore Marina Bay",
    breadcrumb: ["Home", "Singapore", "Singapore Visa"],
    title: "Singapore",
    flag: "🇸🇬",
    country: "Singapore",
    subtitle: "for Indians",
    pills: [
      { icon: "🛡️", text: "Guaranteed in", strong: "7 days" },
      { text: "💻 Online Application" },
      { text: "🔒 100% Refund Policy" },
    ],
    stats: [
      ["18K+", "Visas Processed"],
      ["7 Days", "Guaranteed"],
      ["4.9★", "5K+ Reviews"],
      ["₹4,800", "Govt Fee Only"],
    ],
    guaranteeText: "Guaranteed by 14th Mar, 05:00 PM",
    fasterText: "Same day faster",
    govFee: 4800,
    svcFee: 999,
    svcOrig: 1500,
    visaTypes: ["Tourism", "Business", "Transit"],
    visaInfo: [
      { icon: "📱", label: "Visa Type",      value: "SVP",       link: false },
      { icon: "📅", label: "Length of Stay", value: "30 days",   link: true  },
      { icon: "✅", label: "Validity",        value: "30 days",   link: true  },
      { icon: "🚪", label: "Entry",           value: "Single",    link: true  },
      { icon: "📂", label: "Method",          value: "Online",    link: true  },
    ],
    timeslots: [
      { days: "7 days", date: "14 Mar 2026", time: "05:00 PM" },
      { days: "8 days", date: "15 Mar 2026", time: "10:00 AM" },
      { days: "9 days", date: "16 Mar 2026", time: "02:00 PM" },
    ],
    slotSectionTitle: "Get a Guaranteed Visa on",
    emirates: [
      { name: "Marina Bay",       img: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&q=80" },
      { name: "Sentosa Island",   img: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&q=80" },
      { name: "Gardens by Bay",   img: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=600&q=80" },
      { name: "Orchard Road",     img: "https://images.unsplash.com/photo-1565967511849-76a60a516170?w=600&q=80" },
      { name: "Chinatown",        img: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&q=80" },
      { name: "Little India",     img: "https://images.unsplash.com/photo-1571406955703-84c8d6d52d63?w=600&q=80" },
      { name: "Clarke Quay",      img: "https://images.unsplash.com/photo-1541417904950-b855846fe074?w=600&q=80" },
    ],
    emiratesSectionTitle: "Top Attractions Covered",
    requirements: [
      { icon: "🛂", title: "Passport",          desc: "Valid for at least 6 months beyond your intended stay" },
      { icon: "🖼️", title: "Passport Photo",    desc: "Recent colour photo, white background, 35mm x 45mm" },
      { icon: "✈️", title: "Return Ticket",     desc: "Confirmed onward or return flight" },
      { icon: "🏨", title: "Hotel Booking",     desc: "Confirmed hotel or host accommodation letter" },
      { icon: "💳", title: "Bank Statement",    desc: "Last 3 months — minimum ₹75,000 recommended" },
      { icon: "👔", title: "Employment Proof",  desc: "Salary slips or employer letter (for employed applicants)" },
    ],
    partners: [
      { abbr: "ICA",  name: "Immigration & Checkpoints Authority", color: "#c00" },
      { abbr: "STB",  name: "Singapore Tourism Board",             color: "#e87722" },
      { abbr: "IATA", name: "International Air Transport",         color: "#00538b" },
    ],
    steps: [
      { icon: "📝", num: "01", title: "Apply on TheVisa",    desc: "Fill in the online form and upload documents — pay only government fee upfront." },
      { icon: "🔍", num: "02", title: "Documents Verified",    desc: "Expert review to ensure ICA-compliant application before submission." },
      { icon: "⚙️", num: "03", title: "ICA Processing",        desc: "We track and coordinate with the Singapore ICA for timely processing." },
      { icon: "🎉", num: "04", title: "Visa Delivered",        desc: "Receive your Singapore SVP via email — print and present at arrival." },
    ],
    reviews: [
      { name: "Kavya Suresh",  flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Singapore trip sorted!",         body: "Got my Singapore visa in 6 days, one day before the guarantee. Super smooth process. Will definitely use again for my next trip!" },
      { name: "Rajesh Kumar",  flag: "🇮🇳", rating: 5, date: "Jan 2026", title: "Excellent service",              body: "Applied for family of 3. All three visas came together. Clear communication at every step. Truly impressed!" },
      { name: "Sunita Rao",    flag: "🇮🇳", rating: 4, date: "Mar 2026", title: "Good but slightly pricey",       body: "Service was great and very professional. Cost is a bit high but you do get what you pay for — peace of mind." },
      { name: "Manish Gupta",  flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Zero stress, total trust",      body: "Used TheVisa after a bad experience elsewhere. Night and day difference. Transparent, fast and reliable." },
    ],
    reviewScore: "4.9",
    reviewCount: "5,000+",
    faqs: [
      { q: "Do Indians need a visa for Singapore?",              a: "Yes, Indian passport holders require a visa to enter Singapore. Apply online through TheVisa — guaranteed in 7 days." },
      { q: "What is the Singapore visa fee for Indians?",        a: "Government fee: ₹4,800 (paid upfront). TheVisa service fee: ₹999 (after approval). Total: ₹5,799." },
      { q: "How long can I stay in Singapore?",                  a: "A standard Singapore tourist visa allows a 30-day stay. Extensions are rarely granted — plan your trip accordingly." },
      { q: "Can I apply for a multiple-entry Singapore visa?",   a: "Yes, multiple-entry visas are available for frequent travellers. Eligibility depends on travel history. Our team can advise." },
      { q: "What is the minimum bank balance for Singapore?",    a: "The ICA recommends at least SGD 1,000 (approx ₹62,000) per person per week of stay in your account." },
    ],
    authBadge: "TheVisa is an authorised agent for Singapore ICA applications",
    destinationGridTitle: "Top Attractions Covered",
  },

  "malaysia": {
    heroImg: "https://images.unsplash.com/photo-1596422846543-75c6fc197f11?w=1600&q=85",
    heroAlt: "Kuala Lumpur Malaysia",
    breadcrumb: ["Home", "Malaysia", "Malaysia Visa"],
    title: "Malaysia",
    flag: "🇲🇾",
    country: "Malaysia",
    subtitle: "for Indians",
    pills: [
      { icon: "🛡️", text: "Guaranteed in", strong: "3 days" },
      { text: "📱 eNTRI / eVisa" },
      { text: "🔒 100% Refund Policy" },
    ],
    stats: [
      ["31K+", "Visas Processed"],
      ["3 Days", "Guaranteed"],
      ["4.8★", "7K+ Reviews"],
      ["₹1,800", "Govt Fee Only"],
    ],
    guaranteeText: "Guaranteed by 10th Mar, 04:00 PM",
    fasterText: "6 hrs faster",
    govFee: 1800,
    svcFee: 599,
    svcOrig: 999,
    visaTypes: ["Tourism", "Business", "eNTRI"],
    visaInfo: [
      { icon: "📱", label: "Visa Type",      value: "eNTRI/eVisa", link: false },
      { icon: "📅", label: "Length of Stay", value: "15 days",     link: true  },
      { icon: "✅", label: "Validity",        value: "30 days",     link: true  },
      { icon: "🚪", label: "Entry",           value: "Single",      link: true  },
      { icon: "📂", label: "Method",          value: "Paperless",   link: true  },
    ],
    timeslots: [
      { days: "3 days", date: "10 Mar 2026", time: "04:00 PM" },
      { days: "3 days", date: "10 Mar 2026", time: "07:00 PM" },
      { days: "4 days", date: "11 Mar 2026", time: "12:00 PM" },
    ],
    slotSectionTitle: "Get a Guaranteed Visa on",
    emirates: [
      { name: "Kuala Lumpur", img: "https://images.unsplash.com/photo-1596422846543-75c6fc197f11?w=600&q=80" },
      { name: "Penang",       img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80" },
      { name: "Langkawi",     img: "https://images.unsplash.com/photo-1586861203927-800a5acdcc4d?w=600&q=80" },
      { name: "Malacca",      img: "https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=600&q=80" },
      { name: "Kota Kinabalu", img: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80" },
      { name: "Cameron Highlands", img: "https://images.unsplash.com/photo-1540541338537-b3e3ee5b99bb?w=600&q=80" },
      { name: "Johor Bahru",  img: "https://images.unsplash.com/photo-1587394785568-a2e3b72b9c0f?w=600&q=80" },
    ],
    emiratesSectionTitle: "Top Destinations in Malaysia",
    requirements: [
      { icon: "🛂", title: "Passport",          desc: "Valid for at least 6 months with at least 2 blank pages" },
      { icon: "🖼️", title: "Passport Photo",    desc: "Recent photo on white background" },
      { icon: "✈️", title: "Return Ticket",     desc: "Confirmed onward or return flight booking" },
      { icon: "🏨", title: "Hotel Booking",     desc: "Confirmed accommodation details" },
      { icon: "💳", title: "Bank Statement",    desc: "Last 3 months — sufficient balance for your trip" },
    ],
    partners: [
      { abbr: "IMAN", name: "Immigration Dept Malaysia",     color: "#00529b" },
      { abbr: "MTDC", name: "Malaysia Tourism Dev Corp",     color: "#c00" },
      { abbr: "IATA", name: "International Air Transport",   color: "#00538b" },
    ],
    steps: [
      { icon: "📝", num: "01", title: "Apply on TheVisa",    desc: "Fill the form and upload documents — only pay the government fee upfront." },
      { icon: "🔍", num: "02", title: "Documents Reviewed",    desc: "Our experts verify everything is correct before submitting to Malaysian Immigration." },
      { icon: "⚙️", num: "03", title: "eVisa Processed",       desc: "We track your application with Malaysian Immigration in real time." },
      { icon: "🎉", num: "04", title: "eVisa Delivered",       desc: "Receive the approval letter via email — present it digitally at the airport." },
    ],
    reviews: [
      { name: "Aishwarya Joshi", flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Cheapest + fastest!",          body: "Malaysia eNTRI done in under 3 days at the lowest possible cost. TheVisa is the best — no other service comes close!" },
      { name: "Deepak Choudhary", flag: "🇮🇳", rating: 5, date: "Jan 2026", title: "Really easy process",        body: "Applied at 10pm, got the eNTRI by next afternoon. Support team replied within minutes. Excellent!" },
      { name: "Preethi Rajan",    flag: "🇮🇳", rating: 4, date: "Mar 2026", title: "Good for budget trips",      body: "Malaysia eNTRI via TheVisa was the most affordable option I found. Worked perfectly on arrival at KLIA." },
      { name: "Sanjay Jain",     flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Simple and transparent",     body: "Clear pricing, no surprises. Got both my wife's and my eNTRI together. Would use again in a heartbeat." },
    ],
    reviewScore: "4.8",
    reviewCount: "7,000+",
    faqs: [
      { q: "Do Indians need a visa for Malaysia?",              a: "Indians require either an eNTRI (for direct flights) or an eVisa. TheVisa processes both — guaranteed in 3 days." },
      { q: "What is the Malaysia eNTRI fee for Indians?",       a: "Government fee: ₹1,800. TheVisa service fee: ₹599 (after approval). Total: ₹2,399. Very affordable." },
      { q: "What is the difference between eNTRI and eVisa?",   a: "eNTRI is for direct air travel from India to Malaysia (15 days stay). eVisa covers surface entry and indirect flights (30 days stay). Our team will advise the right one." },
      { q: "How long can I stay in Malaysia on eNTRI?",         a: "The eNTRI permits a 15-day stay and is valid for 90 days from issuance. It cannot be extended." },
      { q: "Can I enter Malaysia via land border with eNTRI?",  a: "No, eNTRI is only valid for air entry. For land entry, you need a full eVisa. Contact our team to upgrade." },
    ],
    authBadge: "TheVisa is a registered agent for Malaysian eVisa applications",
    destinationGridTitle: "Top Destinations in Malaysia",
  },

  "usa": {
    heroImg: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=1600&q=85",
    heroAlt: "New York USA",
    breadcrumb: ["Home", "USA", "US Visa"],
    title: "USA",
    flag: "🇺🇸",
    country: "United States",
    subtitle: "B1/B2 Tourist Visa",
    pills: [
      { icon: "🛡️", text: "Expert Assistance" },
      { text: "📋 Document Review" },
      { text: "🔒 100% Refund Policy" },
    ],
    stats: [
      ["12K+", "Visas Processed"],
      ["99%",  "Doc Accuracy"],
      ["4.8★", "3K+ Reviews"],
      ["₹14,500", "Govt Fee Only"],
    ],
    guaranteeText: "Application submitted in 24 hours",
    fasterText: "Priority filing",
    govFee: 14500,
    svcFee: 1999,
    svcOrig: 2999,
    visaTypes: ["Tourism (B2)", "Business (B1)", "B1/B2 Combined"],
    visaInfo: [
      { icon: "📋", label: "Visa Type",      value: "B1/B2",     link: false },
      { icon: "📅", label: "Length of Stay", value: "Up to 180d", link: true  },
      { icon: "✅", label: "Validity",        value: "10 years",  link: true  },
      { icon: "🚪", label: "Entry",           value: "Multiple",  link: true  },
      { icon: "🏛️", label: "Method",          value: "Embassy",   link: true  },
    ],
    timeslots: [
      { days: "Submit docs", date: "Tomorrow",    time: "By 9:00 AM" },
      { days: "DS-160 filed", date: "Within 24h", time: "Guaranteed"  },
      { days: "Slot booking", date: "We assist",  time: "Earliest available" },
    ],
    slotSectionTitle: "How We Help You",
    emirates: [
      { name: "New York",       img: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=600&q=80" },
      { name: "Los Angeles",    img: "https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=600&q=80" },
      { name: "Las Vegas",      img: "https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=600&q=80" },
      { name: "San Francisco",  img: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=600&q=80" },
      { name: "Miami",          img: "https://images.unsplash.com/photo-1605723517503-3cadb5818a0c?w=600&q=80" },
      { name: "Chicago",        img: "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=600&q=80" },
      { name: "Washington DC",  img: "https://images.unsplash.com/photo-1501466044931-62695aada8e9?w=600&q=80" },
    ],
    emiratesSectionTitle: "Popular US Destinations",
    requirements: [
      { icon: "🛂", title: "Valid Passport",        desc: "Must be valid for at least 6 months beyond your stay period" },
      { icon: "📋", title: "DS-160 Form",           desc: "Completed online application form — we help you fill it accurately" },
      { icon: "🖼️", title: "Passport Photo",        desc: "5x5 cm, white background, taken within 6 months" },
      { icon: "💳", title: "Bank Statement",        desc: "Last 6 months — strong balance significantly improves approval" },
      { icon: "👔", title: "Employment / ITR Docs", desc: "Employer letter, salary slips, or ITR for last 3 years" },
      { icon: "✈️", title: "Itinerary",             desc: "Detailed travel plan including flights and accommodation" },
    ],
    partners: [
      { abbr: "DOS",  name: "Dept of State, USA",         color: "#002868" },
      { abbr: "CGI",  name: "CGI Federal (VFS Partner)",  color: "#8b1a1a" },
      { abbr: "IATA", name: "International Air Transport", color: "#00538b" },
    ],
    steps: [
      { icon: "📝", num: "01", title: "DS-160 & Application",  desc: "We help complete and review your DS-160 form perfectly before submission." },
      { icon: "🔍", num: "02", title: "Document Checklist",    desc: "Our US visa experts prepare a personalised checklist and review all documents." },
      { icon: "📅", num: "03", title: "Interview Preparation", desc: "Mock interview sessions and tips to maximise your chances of approval." },
      { icon: "🎉", num: "04", title: "Visa Collection",       desc: "Passport with visa delivered to your doorstep after embassy approval." },
    ],
    reviews: [
      { name: "Harish Iyer",    flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Got my 10-year US visa!",       body: "TheVisa's document checklist was incredibly thorough. Interview prep sessions were really helpful. Got my B1/B2 approved first attempt!" },
      { name: "Nalini Sharma",  flag: "🇮🇳", rating: 5, date: "Jan 2026", title: "Brilliant support team",       body: "The TheVisa team was with me every step. DS-160 filled correctly, documents perfect — visa approved without issues." },
      { name: "Ramesh Pillai",  flag: "🇮🇳", rating: 4, date: "Mar 2026", title: "Very helpful interview prep", body: "The mock interview was exactly like the real thing. Only 4 questions at the embassy! Couldn't have done it without TheVisa." },
      { name: "Asha Murthy",    flag: "🇮🇳", rating: 5, date: "Feb 2026", title: "Family US visa sorted!",      body: "Applied for 4 family members. All four got their US visas with TheVisa's help. Absolutely stellar service!" },
    ],
    reviewScore: "4.8",
    reviewCount: "3,000+",
    faqs: [
      { q: "How long does a US B1/B2 visa take for Indians?",   a: "Processing times vary by consulate — typically 2-6 weeks after the interview. TheVisa helps get the earliest available interview slot." },
      { q: "What is the US visa fee for Indians?",              a: "Government (MRV) fee: ₹14,500 (non-refundable). TheVisa service fee: ₹1,999 (post-approval). We do NOT charge any fee if your visa is rejected." },
      { q: "Is the US B1/B2 visa valid for 10 years?",          a: "If approved, most Indian applicants receive a 10-year multiple-entry B1/B2 visa. Duration is at the consular officer's discretion." },
      { q: "What is the US visa interview like?",               a: "The interview is typically 2-5 minutes. TheVisa provides comprehensive mock interview preparation and likely questions for your profile." },
      { q: "Can TheVisa guarantee US visa approval?",         a: "No one can guarantee US visa approval — it's at the sole discretion of the consular officer. However, TheVisa maximises your chances with perfect documentation and interview prep." },
    ],
    authBadge: "TheVisa is an authorised US visa application facilitator",
    destinationGridTitle: "Popular US Destinations",
  },
};

/**
 * Get visa data by ID.
 * @param {string} visaId - one of the keys in DATA above
 * @returns {object} visa page data, or UAE-30 as default
 */
export function getVisaData(visaId) {
  return DATA[visaId] || DATA["uae-30"];
}

export default DATA;